
name: studio-nuxt-build
run-name: studio nuxt build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Generate
        run: bun run build
        env:
          NITRO_PRESET: node
          NUXT_CONTENT_PREVIEW_API: https://api.nuxt.studio
